spring:
  data:
    mongodb:
      username: root
      password: root
      host: localhost
      port: 27017
      database: graphql-practice
      # MongoDB doesn't create a new database until actual data comes,
      # so we need to specify initial database for authentication.
      authentication-database: admin
